### ISSUE TITLE
添加参数用于标记访问来自二维码

### ISSUE THREAD

**Issue by taozuhong** [openHacking/vuepress-plugin-qrcode#2]
## 添加参数用于标记访问来自二维码，便于统计效果

可选参数形式：
url?os=ios&channel=qrcode

或者：
url?os=ios&ch=qrcode

**Comment by openHacking** [comment]
很好的想法

**Comment by openHacking** [comment]
@taozuhong 最新1.0.7版本已经更新此功能。

在线demo可以查看效果： https://lwebapp.com/vuepress-template/zh/

注：os的标记我没有加，我感觉移动端设备类型的访问统计通过自定义的js统计代码可以直接获取，不需要在QR code上做。
